### ISSUE TITLE
Detect only TE initiated transcripts

### ISSUE THREAD

**Issue by ngualand** [OliveiraDS-hub/ChimeraTE#18]
Hi,

Thanks for the great tool. I'm analyzing a very large dataset and chimeraTE Is running for a very long time. I'm interested only in TE initiated transcripts, I'd likes to know if I can run the tool to detect only TE initiated transcripts to save computational time?

Thanks

**Comment by OliveiraDS-hub** [comment]
Dear @ngualand 

ChimeraTE has been updated to version 1.2. Now you have the optional parameter `--chimera`, in which you can select TE-initiated and then obtain only TE-initiated transcripts on your results.

And for sure you will save a lot of computational time.

Closing this issue, feel free to reopen if you need

Cheers

**Comment by ngualand** [comment]
Thank you very much for the update,

Nicolò
