### ISSUE TITLE
Questions while install the ChimeraTE

### ISSUE THREAD

**Issue by Orz-CQ** [OliveiraDS-hub/ChimeraTE#2]
Hi,

I have great interest about the Chimera! I think it may help me find some interesting results in another view.
While I am trying to install it, I met some question.

1) Using conda.
The error is 
```
Encountered problems while solving:
  - package perl-pathtools-3.40-0 requires perl >=5.22.0,<5.23.0, but none of the providers can be installed
```
And I tried the different perl version, or through installed the software listed in the chimeraTE.yml, the example data could not successfully run.

2) So I truned to the docker.
Unfortunately, I cannot use docker. So will ChimeraTE could be used through the singularity?

Thanks!

Lan

**Comment by OliveiraDS-hub** [comment]
Hello @Orz-CQ, I apprecciate your interest in use ChimeraTE

Unfortunately, you are not the first researcher to contact me about problems during installation process. Currently ChimeraTE is written in bash, which means that depending on your linux system, you might have problems. We did the docker to mitigate it, but in your case is useless.

What is your operational system? One thing that you can do, that will solve all the problems (it's supposed to) is to install a virtual machine with Ubuntu 18, then install ChimeraTE in this VM.

Anyway, if you are not in a hurry, we are writing ChimeraTE in python, and with that the compatibility with other machines will be much better. Furthermore, substantial changes in ChimeraTE script have been done. The pipeline is currently under review and modifications include several modifications on how results are predicted, including removal of false positives.

**Comment by Orz-CQ** [comment]
Thanks for your reply and sorry for my late responding.

Here is my operational system
`Linux mgt02 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`

Maybe I could wait for the new pipeline.
And I am willing to test the new pipeline if you have already finished the re-writing work!

By the way, I am going to study the TE in plants, so I am insterested about the ChimeraTE, if you need anything else please let me know.

Lan

**Comment by zuodabin** [comment]
And then I found a good way to do this, which is first 
**
[chimeraTE.txt](https://github.com/OliveiraDS-hub/ChimeraTE/files/10804001/chimeraTE.txt)
conda create  -n ChimeraTE
conda activate ChimeraTE
conda install --yes --file chimeraTE.txt
**
I uploaded this file

**Comment by Orz-CQ** [comment]
Got it!
Thanks for your advices.

**Comment by Orz-CQ** [comment]
Hi @OliveiraDS-hub 
I have seen that the ChimeraTE has updated to v1.1!
Does it is a right time to install and test this pipeline?
Looking forward for your reply

Lan

**Comment by OliveiraDS-hub** [comment]
Hello @Orz-CQ 

The second round of review is taking more time than expected, but we are almost done. Currently we are just waiting the suggestions from a few co-authors. Very soon we'll update the version on bioarchive and then officially the github repo will be ready to use.

I'll let you know when it's officially ready.

We appreciate your interest!

**Comment by OliveiraDS-hub** [comment]
Dear @Orz-CQ 

ChimeraTE has been accepted and the paper will be available soon on Nucleic and Acids Research. The repo is currently being updated, but the code is on its last version.

Closing this issue.

Best regards
