### ISSUE TITLE
Coverage definition

### ISSUE THREAD

**Issue by giulialopatriello95** [OliveiraDS-hub/ChimeraTE#24]
Hi there,

I would like to ask for the exact definition of chimeric reads reported in the output of analysis mode 1. Does this number represent an estimated average coverage across the analyzed replicates where the fusion is present, or is it the sum of coverage across replicates?

Additionally, I was wondering if 20 million RNA-Seq fragments provide sufficient coverage to perform the analysis.

Best regards,
Giulia

**Comment by OliveiraDS-hub** [comment]
Hi Giulia,

Yes, "chimeric_reads" stands for the average number of reads supporting the chimeric transcript between replicates. It's not the sum of reads.

If 20M reads is enough will depend on many aspects of your data: species, number of genes, tissue-specific or not, number of replicates...  For Drosophila, in tissue-specific data, 20M is usually a fair amount of reads.

Best
