### ISSUE TITLE
How to understand the meaning of exonized_type?

### ISSUE THREAD

**Issue by Orz-CQ** [OliveiraDS-hub/ChimeraTE#7]
Hi,

I am confused about how to understand the exonized_type.
What are the meaning of "Embedded", "Overlapped" and "Intronic".

If the "Intronic" means the TEs insert into the intron, and support by the chimeric reads?
If the "Embedded" means the TEs insert into the whole gene region and may cross both the exon and intron region?

Thanks in advance!

Lan

**Comment by OliveiraDS-hub** [comment]
Hi @Orz-CQ!

The exonized type is regarding the position of the TE insertion compared to the exons. All exonizations are supported by chimeric reads.

The classification is demonstrated on the supp. figure 1 of our paper:

![mm_figure_FINAL](https://github.com/OliveiraDS-hub/ChimeraTE/assets/15055555/e935a896-0d4a-4464-9e5e-a4be3a2f191b)

Let me know if it's clear now, then I can close the issue

**Comment by Orz-CQ** [comment]
Sorry I cannot find this supp. figure1 from the bioRxiv.
This plot has completely answer my questions.
Thanks for your quickly response!

**Comment by OliveiraDS-hub** [comment]
Probably you are looking for ir in the first version of the manuscript. On BioRxiv, check if there is a red button "View current version of this article" on the top-left of the title, or check it out here:
 
[https://www.biorxiv.org/content/10.1101/2022.09.05.505575v2](url)

The figure is in the docx file in the supp material.

Thank you for your feedback! I'm closing this issue. Do not hesitate to open another if have questions.

Best
