### ISSUE TITLE
Error with bedfile

### ISSUE THREAD

**Issue by Ifengel** [OliveiraDS-hub/ChimeraTE#8]
Hello, 

I got the following error: 

The command was:

	bedtools intersect -a /mnt/nvme0n1p1/ifengel/ChimeraTE/projects/chimera_test/tmp/TE_file.bed -wa -nonamecheck -b /mnt/nvme0n1p1/ifengel/ChimeraTE/projects/chimera_test/rep1/alignment/accepted_hits.bed

The error message was:
Error: unable to open file or unable to determine types for file /mnt/nvme0n1p1/ifengel/ChimeraTE/ChimeraTE/projects/prueba_quimera/tmp/TE_file.bed

- Make sure your file is TAB delimited (for example, cat -t FILE).
- Also make sure that your file has integer chromosome coordinates in the expected columns (e.g., col 
  expected columns (e.g. cols 2 and 3 for BED).

My .bed file has the following format (which is created by the pipeline itself):

8	chr1	8386825	-	.	-187082416
52	chr1	16776988	+	.	-178692920
91	chr1	33554408	-	.	-161917331
0	chr1	50329971	+	.	-145136573
0	chr1	83885790	-	.	-111585613
0	chr1	109051332	+	.	-86419645
15	chr1	125828927	+	.	-69642495
11	chr1	167772060	-	.	-27699727
0	chr1	184549326	+	.	-10922519
49	chr1	3145673	-	.	-192326175

I don't know how I can to fix this error.

**Comment by OliveiraDS-hub** [comment]
Dear @Ifengel, the bed file doesn't follow the correct order of columns. Probably the gtf file for TEs that you provided is not well formatted. 

The right conversion from .out (output from RepeatMasker) to .gtf can be done with the following command line:

`tail -n +4 RMfile.out | egrep -v 'Satellite|Simple_repeat|rRNA|Low_complexity|RNA|ARTEFACT' | awk -v OFS='\t' '{Sense=$9;sub(/C/,"-",Sense);$9=Sense;print $5,"RepeatMasker","similarity",$6,$7,$2,$9,".",$10}' > RMfile.gtf`

You can try to use the `RMfile.gtf` as input to fix the error.

If the error is still happening, could you send me the first lines of your gtf for TEs?

**Comment by Ifengel** [comment]
Hello again,

The error still happening. Im going to show you my .out and my gtf... I don't know where is the fail. 

File .out from RepeatMasker:

#bin	swScore	milliDiv	milliDel	milliIns	genoName	genoStart	genoEnd	genoLeft	strand	repName	repClass	repFamily	repStart	repEnd	repLeft	id
0	239	248	8	62	chr1	67108752	67108881	-128363090	+RLTR17B_Mm	LTR	ERVK	329	450	-352	1
0	230	346	25	0	chr1	134217651	134217732	-61254239	-BC1_Mm	scRNA	scRNA	-56	96	14	2
1	8310	151	115	8	chr1	8386825	8389555	-187082416	-	Lx2	LINE	L1	0	6997	3977	7
1	32159	86	8	52	chr1	16776988	16779051	-178692920	+L1_Mus1	LINE	L1	4513	6565	-2	2
1	216	318	73	91	chr1	33554408	33554640	-161917331	-B4	SINE	B4	-48	244	17	4
1	200	211	19	0	chr1	41943029	41943081	-153528890	+(CA)n	Simple_repeat	Simple_repeat	2	54	0	6


With this .out and the commands that you sent me, I obtained this gtf file:

8	RepeatMasker	similarity	chr1	8386825	8310	-187082416	.	-
52	RepeatMasker	similarity	chr1	16776988	32159	-178692920	.	+
91	RepeatMasker	similarity	chr1	33554408	216	-161917331	.	-
0	RepeatMasker	similarity	chr1	50329971	28308	-145136573	.	+
0	RepeatMasker	similarity	chr1	83885790	4868	-111585613	.	-
0	RepeatMasker	similarity	chr1	109051332	8314	-86419645	.	+
15	RepeatMasker	similarity	chr1	125828927	3167	-69642495	.	+
11	RepeatMasker	similarity	chr1	167772060	493	-27699727	.	-
0	RepeatMasker	similarity	chr1	184549326	584	-10922519	.	

Thank u in advance!
